[2022-07-30 17:49:43,572] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-07-30T16:44:00+00:00 [queued]>
[2022-07-30 17:49:43,579] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-07-30T16:44:00+00:00 [queued]>
[2022-07-30 17:49:43,580] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-07-30 17:49:43,580] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-07-30 17:49:43,580] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-07-30 17:49:43,592] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): tweets_to_es> on 2022-07-30 16:44:00+00:00
[2022-07-30 17:49:43,595] {standard_task_runner.py:52} INFO - Started process 11442 to run task
[2022-07-30 17:49:43,598] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'tweets_to_es', 'scheduled__2022-07-30T16:44:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/airfow_es.py', '--cfg-path', '/tmp/tmpjxj0ozr1', '--error-file', '/tmp/tmpycxnwc1q']
[2022-07-30 17:49:43,599] {standard_task_runner.py:80} INFO - Job 26: Subtask tweets_to_es
[2022-07-30 17:49:43,633] {task_command.py:370} INFO - Running <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-07-30T16:44:00+00:00 [running]> on host oury-Tp
[2022-07-30 17:49:43,677] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=tweets_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-07-30T16:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-30T16:44:00+00:00
[2022-07-30 17:49:43,679] {twitter.py:696} INFO - Retrieving scroll page None
[2022-07-30 17:49:43,679] {twitter.py:626} INFO - Retrieving guest token
[2022-07-30 17:49:43,680] {base.py:171} INFO - Retrieving https://twitter.com/search?f=live&lang=en&q=near%3AParis+since%3A1659199440+until%3A1659199680&src=spelling_expansion_revert_click
[2022-07-30 17:49:44,201] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 11442. PIDs of all processes in the group: [11442]
[2022-07-30 17:49:44,201] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 11442
[2022-07-30 17:49:44,201] {taskinstance.py:1542} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-07-30 17:49:44,207] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/oury/airflow/dags/airfow_es.py", line 79, in tweet_to_es_func
    for i, tweet in enumerate(twitter.TwitterSearchScraper(f'near:{location} since:{start_time} until:{end_time}').get_items()):
  File "/home/oury/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1405, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/home/oury/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 697, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/home/oury/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 664, in _get_api_data
    self._ensure_guest_token()
  File "/home/oury/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 627, in _ensure_guest_token
    r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent}, responseOkCallback = self._check_guest_token_response)
  File "/home/oury/.local/lib/python3.10/site-packages/snscrape/base.py", line 221, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/oury/.local/lib/python3.10/site-packages/snscrape/base.py", line 178, in _request
    r = self._session.send(req, allow_redirects = allowRedirects, timeout = timeout, **environmentSettings)
  File "/home/oury/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/oury/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/oury/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/oury/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/oury/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1544, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-07-30 17:49:44,221] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=tweets_to_es, execution_date=20220730T164400, start_date=20220730T164943, end_date=20220730T164944
[2022-07-30 17:49:44,233] {standard_task_runner.py:92} ERROR - Failed to execute job 26 for task tweets_to_es (Task received SIGTERM signal; 11442)
[2022-07-30 17:49:44,253] {process_utils.py:75} INFO - Process psutil.Process(pid=11442, status='terminated', exitcode=1, started='17:49:43') (11442) terminated with exit code 1
